name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          curl -Ls https://github.com/jgm/pandoc/releases/download/2.11.2/pandoc-2.11.2-1-amd64.deb -o pandoc.deb
          sudo dpkg -i pandoc.deb
          sudo apt-get install fonts-stix
          sudo apt-get install libunistring-dev

      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: '8.14'

      # - name: Test
      #   run: raco test

      - name: Build website
        run: |
          xvfb-run -a raco scribble --htmls ++style css/fancyverb.css ++xref-in setup/xref load-collections-xref --redirect-main http://docs.racket-lang.org/ main.scrbl
          cp -r examples main/

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: main/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
